### ISSUE TITLE
why are all the "required" dependencies peerDeps?

### ISSUE THREAD

**Issue by joebartels-tw** [transferwise/eslint-config#3]
Many of the peerDeps look like real dependencies that should be "shipped" with this package.

e.g. eslint, eslint-config-airbnb, eslint-config-prettier, and prettier (maybe some of the plugins too).

This library is only nice in-so-much as it creates consistency among projects. But, relying on `peerDependencies` works _against_ consistency. i.e. over time projects will update their **eslint**, **eslint-config-airbnb**, etc. independently of **@transferwise/eslint-config**

we're talking about the difference of updating 1 package
```json
{
  "devDependencies": {
    "@transferwise/eslint-config": "0.4.0"
  }
}
```
vs updating maaaany packages 
```json
{
  "devDependencies": {
    "@transferwise/eslint-config": "^0.4.0",
    "eslint": "^5.16.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-config-prettier": "^4.2.0",
    "eslint-plugin-import": "^2.17.2",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-prettier": "^3.0.1",
    "eslint-plugin-react": "^7.13.0",
    "husky": "^2.2.0"
  }
}
```

**Comment by oliverviljamaa** [comment]
Thanks for flagging this!

I completely agree, as much as possible should be put in `dependencies`, _especially_ the configs for the reasons you mentioned. There is no reason why this isn't done, it's just that no one has worked on it yet 😊 PRs are much appreciated!

If I understand and remember correctly, configs and parsers should work as `dependencies`, but `eslint`, `prettier`, and plugins need to be `peerDependencies` [(ESLint documentation)](https://eslint.org/docs/developer-guide/shareable-configs#publishing-a-shareable-config). From personal experience, I remember having problems with `babel-eslint` being in `dependencies`, but that may have just been due to faulty `npm link`ing.

I also think that `husky` and `lint-staged` don't necessarily belong in `peerDependencies`. The initial rationale was that they'd then get installed in one go with `install-peerdeps`, but it's not correct in terms of meaning (linting is not _dependent_ on commit hooks). Therefore, I believe they should be removed from `peerDependencies` and the readme should just be updated to have a step for `npm install husky lint-staged`.

**Comment by oliverviljamaa** [comment]
`eslint-config-airbnb` and `eslint-config-prettier` were moved from `peerDependencies` to `dependencies` with https://github.com/transferwise/eslint-config/pull/8 😊 

Can we resolve this issue?

**Comment by joebartels-tw** [comment]
the changes look good to me!
